---
title: "Avg_pitch_time_graph"
author: "Ryan Dajani"
date: "2024-07-23"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#loading in the appropriate libraries
```{r}
library(dplyr)
library(ggplot2)
library(gt)
```

#Creating a Table that ranks Pitchers according to their average pitch time
```{r}
#Ranking players based on their pitch velocity

top_pitchers <- result %>%
  group_by(pitcher) %>%
  summarize(MaxVelocity = max(pitch_velo)) %>%
  ungroup() %>%
  arrange(desc(MaxVelocity)) %>%
  mutate(Rank = row_number()) %>%
  slice_head(n = 10)

slowest_pitchers <- result %>%
  group_by(pitcher) %>%
  summarize(MinVelocity = min(pitch_velo)) %>%
  ungroup() %>%
  arrange(MinVelocity) %>%
  mutate(Rank = row_number()) %>%
  slice_head(n = 10)
  
View(slowest_pitchers)

top_pitchers_table <- top_pitchers %>%
  gt() %>%
  tab_header(
    title = "Top 10 Pitchers by Maximum Pitch Velocity"
  )%>%
  cols_label(
    pitcher = "Pitcher ID",
    MaxVelocity = "Maximim Pitch Velocity (MPH)",
    Rank = "Rank"
  )%>%
  tab_options(
    table.font.size = 12
  )
print(top_pitchers_table)

```
